### ISSUE TITLE
Version 1.2 throws error

### ISSUE THREAD

**Issue by gerasym** [linaro-its/aws2-wrap#45] opened 2021-08-18 13:03 UTC
aws2-wrap --profile dev terraform init 

> Traceback (most recent call last): 
>  File "/usr/local/bin/aws2-wrap", line 8, in <module>
>    sys.exit(main())
>TypeError: main() missing 1 required positional argument: 'argv'

**Comment by pcolmer** [comment] 2021-08-18 13:25
Thank you for letting me know about this, and my apologies.

Fixed in https://github.com/linaro-its/aws2-wrap/pull/46 and released as version 1.2.1.

**Comment by gerasym** [comment] 2021-08-18 14:39
Thanks for quick fix :)
With 1.2.1 it works with --exec flag only
without i get the following error
aws2-wrap --profile dev terraform init -backend-config=bucket=bucket-name -var-file=config/test.tfvars
terraforminit-backend-config=bucket=bucket-name-var-file=config/test.tfvars: No such file or directory

**Comment by passing** [comment] 2021-08-18 14:40
I guess the problem is here:
https://github.com/linaro-its/aws2-wrap/blob/master/aws2wrap/__init__.py#L375
arguments need to be joined with a space

**Comment by pcolmer** [comment] 2021-08-18 14:41
Thanks, @passing. That is a change that got introduced this morning to quickly fix a problem introduced elsewhere. I'll make the fix.

**Comment by pcolmer** [comment] 2021-08-18 14:45
Fixed in v1.2.2.

**Comment by sodul** [comment] 2021-08-18 23:14
The bug was my doing, sorry about that!

**Closed as completed** 2021-08-19 10:21 UTC
